   'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useEffect, useRef, type MouseEvent } from 'react'
import { motion } from 'framer-motion'
import { useUser } from '@/lib/userContext'
import { MagneticCard } from '@/components/ui/MagneticCard'
import { Marquee } from '@/components/ui/Marquee'
import { BlurInText } from '@/components/ui/BlurInText'

const MODES = [
  { num: '01', title: 'Speaking Practice', desc: 'AI topics matched to your goal. Speak, get evaluated.',    href: '/practice/topics-home' },
  { num: '02', title: 'Reading Practice',  desc: 'Read aloud at the right pace. Dual cursor feedback.',      href: '/practice/reading'     },
  { num: '03', title: 'Vocabulary',        desc: 'Goal-based words generated by AI. Use them in sentences.', href: '/practice/vocabulary'  },
  { num: '04', title: 'Analytics',         desc: 'Track streaks, WPM, scores, and improvement over time.',   href: '/analytics'            },
] as const


const container = {
  hidden: {},
  show: { transition: { staggerChildren: 0.09, delayChildren: 0.25 } },
}
const item = {
  hidden: { opacity: 0, y: 22 },
  show:   { opacity: 1, y: 0, transition: { duration: 0.55, ease: ['easeOut'] } },
}

const DIFFICULTY_LABELS: Record<string, string> = {
  beginner:     'Beginner',
  intermediate: 'Intermediate',
  advanced:     'Advanced',
}

export default function HomePage() {
  const { profile } = useUser()
  const router      = useRouter()

  // Spotlight that trails the cursor across the mode grid
  const gridRef = useRef<HTMLDivElement>(null)
  const onGridMove = (e: MouseEvent) => {
    const el = gridRef.current
    if (!el) return
    const r = el.getBoundingClientRect()
    el.style.setProperty('--spot-x', `${e.clientX - r.left}px`)
    el.style.setProperty('--spot-y', `${e.clientY - r.top}px`)
  }

  // Redirect to onboarding on first visit
  useEffect(() => {
    if (!profile.setupDone) {
      router.push('/onboarding')
    }
  }, [profile.setupDone])

  if (!profile.setupDone) return null

  return (
    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '0 1.5rem 6rem' }}>

      <motion.div
        style={{ textAlign: 'center', marginTop: 'clamp(5rem, 10vw, 7rem)', marginBottom: 'clamp(4rem, 8vw, 5rem)', maxWidth: '40rem' }}
        initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.7, ease: ['easeOut'] }}
      >
        <p style={{ fontSize: '0.72rem', letterSpacing: '0.18em', textTransform: 'uppercase', color: 'hsl(var(--muted-foreground))', marginBottom: '1.5rem' }}>
          AI Communication Training
        </p>
        <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(2.8rem, 8vw, 5.5rem)', lineHeight: 1.05, letterSpacing: '-0.02em', marginBottom: '1.75rem' }}>
          <BlurInText text="Speak better," />
          <br />
          <motion.em
            className="shimmer"
            style={{ display: 'inline-block' }}
            initial={{ opacity: 0, filter: 'blur(12px)', y: 16 }}
            animate={{ opacity: 1, filter: 'blur(0px)', y: 0 }}
            transition={{ delay: 0.55, duration: 0.6, ease: 'easeOut' }}
          >
            every day.
          </motion.em>
        </h1>

        {/* Current goal context */}
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: '1rem', padding: '0.6rem 1.25rem', border: '1px solid hsl(var(--border))', fontSize: '0.8rem', color: 'hsl(var(--muted-foreground))' }}>
          <span>{DIFFICULTY_LABELS[profile.difficulty]} · {profile.goals.length > 40 ? profile.goals.slice(0, 40) + '…' : profile.goals}</span>
          <Link href="/onboarding"
            style={{ fontSize: '0.72rem', letterSpacing: '0.1em', textTransform: 'uppercase', color: 'hsl(var(--muted-foreground))', textDecoration: 'none' }}
            onMouseEnter={e => (e.currentTarget.style.color = 'hsl(var(--foreground))')}
            onMouseLeave={e => (e.currentTarget.style.color = 'hsl(var(--muted-foreground))')}
          >
            Change
          </Link>
        </div>
      </motion.div>

      <motion.div
        className="mode-grid"
        ref={gridRef}
        onMouseMove={onGridMove}
        style={{ width: '100%', maxWidth: '48rem', display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', borderTop: '1px solid hsl(var(--border))', borderLeft: '1px solid hsl(var(--border))' }}
        variants={container} initial="hidden" animate="show"
      >
        <div className="mode-grid__spot" aria-hidden />
        {MODES.map((mode) => (
          <motion.div key={mode.num} variants={item}>
            <MagneticCard mode={mode} />
          </motion.div>
        ))}
      </motion.div>

      <motion.div
        style={{ width: '100%', maxWidth: '48rem', marginTop: '3.5rem' }}
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.8 }}
      >
        <Marquee items={['Speak boldly', 'Think clearly', 'Sound confident', 'Practice daily']} speed={20} />
      </motion.div>

      <motion.p
        style={{ marginTop: '2.5rem', fontSize: '0.72rem', letterSpacing: '0.15em', textTransform: 'uppercase', color: 'hsl(var(--muted-foreground))' }}
        initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.9 }}
      >
        Powered by Whisper · AI feedback
      </motion.p>
    </div>
  )
}
